### ISSUE TITLE
Frontend: Profile

### ISSUE THREAD

**Issue by sause668** [sause668/stock-trading-app#26]
These are the base components and information need for the page

Portfolios
- [ ] Portfolios list 
- [ ] Portfolios search (might include)
- [ ] New Portfolio Button
- [ ] Edit Portfolio Button
- [ ] Delete Portfolio Button
- [ ] Modal: Create/Edit Portfolio
- [ ] Modal: Delete Portfolio

Watchlist
- [ ] Watchlist
- [ ] Add Stock Button
- [ ] Remove Stock Button
- [ ] Modal: Add Stock
- [ ] Modal: Remove Stock

**Comment by WildChargerTV** [comment]
Using https://robinhood.com/us/en/support/articles/profile/ for reference
